use examination;
show tables;
desc login_student;
desc login_teacher;
-- insert into login_teacher values ("1032221958@mitwpu.edu.in","Manoj","Man@123");
-- insert into login_student values ("1032221958@mitwpu.edu.in","Manoj","Man@123");
-- truncate login_teacher;
select * from login_teacher;
select * from login_student;
desc question_paper;
show tables;
use questions;
show tables;